Projekt_final/urls.py
from django.contrib import admin
from django.urls import path
from vinyl_market.views import RegisterUserView, MainView, LoginUserView, LogOutView, ArtistAddView, AlbumAddView, \
    GenreAddView, AlbumListView, ArtistUpdateView, UserOfferAddView, UserOfferPublicListView, \
    TrackAddView, AlbumUpdateView, AlbumAddManyArtists, AlbumDetailView, AboutView, \
    AlbumDeleteView, MessageSendView, MessageDeleteView, MessagesReceivedView, MessagesSentView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main_view'),
    path('about/', AboutView.as_view(), name='about_view'),
    path('register_user/', RegisterUserView.as_view(), name='register_user_view'),
    path('login/', LoginUserView.as_view(), name='login_view'),
    path('logout/', LogOutView.as_view(), name='logout_view'),
    path('add_artist/', ArtistAddView.as_view(), name='add_artist_view'),
    path('update_artist/<int:pk>/', ArtistUpdateView.as_view(), name='artist_update_view'),
    path('add_album/', AlbumAddView.as_view(), name='add_album_view'),
    path('add_album_manyartists/', AlbumAddManyArtists.as_view(), name='add_album_many_artists'),
    path('delete_album/<int:pk>/', AlbumDeleteView.as_view(), name='delete_album_view'),
    path('add_genre/', GenreAddView.as_view(), name='add_genre_view'),
    path('album_list/', AlbumListView.as_view(), name='album_list_view'),
    path('album_details/<int:pk>/', AlbumDetailView.as_view(), name='album_detail_view'),
    path('add_album_to_market/<int:pk>/', UserOfferAddView.as_view(), name='album_add_to_market_view'),
    path('album_update/<int:pk>/', AlbumUpdateView.as_view(), name='album_update_view'),
    path('album_update/<int:pk>/add_track/', TrackAddView.as_view(), name='track_add_view'),
    path('user_offer_view/', UserOfferPublicListView.as_view(), name='user_offer_public_view'),
    path('messages/', MessagesReceivedView.as_view(), name='messages_view'),
    path('messages_sent/', MessagesSentView.as_view(), name='messages_sent'),
    path('send_message/<int:pk>/', MessageSendView.as_view(), name='sent_message'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='del_message'),



]

vinyl_market/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    username = models.CharField(max_length=128, unique=True)
    email = models.EmailField(max_length=128, unique=True)
    password = models.CharField(max_length=128)


class Artist(models.Model):
    name = models.CharField(max_length=128)
    bio = models.TextField(max_length=1024, blank=True)

    def __str__(self):
        return f"{self.name}"


class Genre(models.Model):
    kind = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"{self.kind}"


class Album(models.Model):
    title = models.CharField(max_length=128)
    label = models.CharField(max_length=128)
    country = models.CharField(max_length=128, blank=True)
    released = models.IntegerField(blank=True)
    artist = models.ManyToManyField(Artist)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.title}"


class Track(models.Model):
    name = models.CharField(max_length=128)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)


class UserOffer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    price = models.SmallIntegerField()


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

vinyl_market/forms.py
from datetime import datetime

import django.forms as forms
from django.forms import ModelForm

from vinyl_market.models import Artist, Genre, Album, Track, Message


class LoginViewForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterUserForm(forms.Form):
    username = forms.CharField(label="Username")
    email = forms.EmailField(label="Email", widget=forms.EmailInput)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class EditUserForm:
    username = forms.CharField(label="New Username")
    email = forms.EmailField(label="Email", widget=forms.EmailInput)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class AlbumAddForm(forms.Form):
    title = forms.CharField(max_length=128)
    label = forms.CharField(max_length=128, required=False)
    country = forms.CharField(max_length=128, required=False)
    released = forms.IntegerField()
    artist = forms.ModelChoiceField(queryset=Artist.objects.all())
    genre = forms.ModelChoiceField(queryset=Genre.objects.all())


class AlbumCreateForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
            'artist': forms.SelectMultiple()
        }


class TrackAddForm(forms.Form):
    name = forms.CharField(max_length=128)
    album = forms.CharField(max_length=128, widget=forms.HiddenInput())


class GenreAddForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['kind']


class UserOfferForm(forms.Form):
    user = forms.CharField(max_length=64)
    album = forms.CharField(max_length=128)
    price = forms.IntegerField()


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['receiver', 'message']

vinyl_market/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from vinyl_market.models import User, Artist, Album, Genre, UserOffer, Message, Track
from vinyl_market.forms import LoginViewForm, RegisterUserForm, AlbumAddForm, \
    TrackAddForm, AlbumCreateForm, MessageForm, GenreAddForm


class MainView(View):
    def get(self, request):
        return render(request, 'main.html')


class AboutView(View):
    def get(self, request):
        return render(request, 'about.html')


class RegisterUserView(View):
    def get(self, request):
        form = RegisterUserForm
        return render(request, 'user_form.html', {'form': form})

    def post(self, request):
        form = RegisterUserForm(request.POST)
        message2 = "User successfully registered. Please login using given credentials"
        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email']
            )
        return render(request, 'main.html', {'message2': message2})


class LoginUserView(View):
    def get(self, request):
        form = LoginViewForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = LoginViewForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                message = "Login successful"
                return render(request, 'main.html', {'message2': message})
            else:
                message = "Invalid login, check your username and password"
                return render(request, 'login.html', {'message2': message, 'form': form})


class LogOutView(View):
    def get(self, request):
        logout(request)
        message = "Logout successful"
        return render(request, 'logout.html', {'message2': message})


class ArtistAddView(LoginRequiredMixin, CreateView):
    model = Artist
    fields = ['name', 'bio']
    success_url = '/add_artist/'

    def get_context_data(self):
        context = super().get_context_data()
        context['artists'] = Artist.objects.all()
        return context


class AlbumAddView(LoginRequiredMixin, FormView):

    def get(self, request):
        form = AlbumAddForm()
        return render(request, 'album_form.html', {'form': form})

    def post(self, request, **kwargs):
        form = AlbumAddForm(request.POST)
        if form.is_valid():
            album = Album.objects.create(
                title=form.cleaned_data['title'],
                label=form.cleaned_data['label'],
                country=form.cleaned_data['country'],
                released=form.cleaned_data['released'],
                genre=form.cleaned_data['genre'],
                user=request.user
            )
            album.artist.add(form.cleaned_data['artist'])
            album.save()
            return redirect('album_list_view')
        else:
            return render(request, 'vinyl_market/album_list.html', {'form': form})


class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = '/album_list/'


class AlbumListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Album.objects.filter(user=self.request.user)


class AlbumDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        album = Album.objects.get(pk=pk)
        return render(request, 'album_detail.html', {'album': album})


class AlbumAddManyArtists(LoginRequiredMixin, View):

    def get(self, request):
        user = self.request.user
        form = AlbumCreateForm(initial={'user': user})
        return render(request, 'album_many_artists_form.html', {'form': form})

    def post(self, request):
        form = AlbumCreateForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            form.save_m2m()
            return redirect('album_list_view')


class AlbumUpdateView(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['title', 'label', 'country', 'released', 'genre']
    template_name_suffix = '_update_form'
    success_url = '/album_list/'


class TrackAddView(LoginRequiredMixin, View):

    def get(self, request, pk):
        album = Album.objects.get(pk=pk)
        form = TrackAddForm()
        return render(request, 'track_add_template.html', {'form': form, 'album': album})

    def post(self, request, pk):
        titles = request.POST.getlist('name')
        if titles != "":
            for title in titles:
                Track.objects.create(name=title, album_id=pk)
            album = Album.objects.get(pk=pk)
            return render(request, 'album_detail.html', {'album': album})
        else:
            return render(request, 'main.html', {'message': "Error. Fill the form correctly"})


class ArtistUpdateView(LoginRequiredMixin, UpdateView):
    model = Artist
    fields = ['name', 'bio']
    template_name_suffix = '_update_form'
    success_url = '/add_artist/'


class GenreAddView(LoginRequiredMixin, View):
    def get(self, request):
        form = GenreAddForm()
        genres = Genre.objects.all()
        return render(request, 'genre_form.html', {'form': form, 'genres': genres})

    def post(self, request):
        form = GenreAddForm(request.POST)
        genres = Genre.objects.all()

        if form.is_valid():
            kind = form.cleaned_data['kind']
            try:
                Genre.objects.get(kind=kind)
                return render(request, 'genre_form.html', {'form': form, 'genres': genres})
            except ObjectDoesNotExist:
                genre = Genre.objects.create(kind=kind)
                genre.save()
        return render(request, 'genre_form.html', {'form': form, 'genres': genres})


class UserOfferAddView(LoginRequiredMixin, View):
    def get(self, request, pk):
        album = Album.objects.get(pk=pk)
        return render(request, 'useroffer_form.html', {'album': album})

    def post(self, request, pk):
        user = request.user
        album = Album.objects.get(pk=pk)
        price = request.POST['price']
        if price != "":
            UserOffer.objects.create(
                user=user,
                album=album,
                price=price,
            )
            return redirect('user_offer_public_view')


class UserOfferPublicListView(ListView):
    model = UserOffer

    def get_queryset(self):
        return UserOffer.objects.all()


class MessagesReceivedView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        messages = Message.objects.filter(receiver=user)
        return render(request, 'messages.html', {'messages': messages})


class MessagesSentView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        messages = Message.objects.filter(sender=user)
        return render(request, 'messages_sent.html', {'messages': messages})


class MessageSendView(LoginRequiredMixin, View):
    def get(self, request, pk):
        receiver = User.objects.get(pk=pk)
        form = MessageForm(initial={'receiver': receiver})
        return render(request, 'send_message.html', {'form': form})

    def post(self, request, pk):
        receiver = User.objects.get(pk=pk)
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.save()
            return redirect('messages_sent')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = '/messages/'

vinyl_market/templates/vinyl_market/album_confirm_delete.html
{% extends 'main.html' %}
{% block content %}

    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete the album  ?</p>
        <p id="artist_list_p">"{{ album.title}}"</p>
        <p id="artist_list_p2"><button type="submit" value="Confirm">Confirm</button></p>

    </form>

{% endblock %}

vinyl_market/templates/vinyl_market/album_list.html
{% extends 'main.html' %}
{% block content %}
    <ul>
        <li><a href={% url 'add_album_view' %}>ADD ALBUM</a></li>
        <li><a href={% url 'add_album_many_artists' %}>ADD MANY ARTIST ALBUM</a></li>
        <li><a href={% url 'add_genre_view' %}>ADD GENRE</a></li>
    </ul>

    <table>
        <th>Artist</th>
        <th>Album</th>
        <th>Release date</th>
        <th>Add to market</th>

    {% for album in object_list %}
        {% for artist in album.artist.all %}
                <tr>
                <td><a href={% url 'artist_update_view' artist.id %}>{{ artist.name }}</a></td>
                <td><a href={% url 'album_detail_view' album.id %}>{{ album.title }}</a></td>
                <td>{{ album.released }}</td>
                <td><a href={% url 'album_add_to_market_view' album.id %}>&#9737</a></td>
            </tr>
        {% endfor %}
        {% empty %}
            <p>No albums yet.</p>
    {% endfor %}
    </table>
{% endblock %}

vinyl_market/templates/vinyl_market/album_update_form.html
{% extends 'main.html' %}
{% block content %}
    <ul>
        <li><a href={% url 'track_add_view' album.id %}>ADD TRACKS</a></li>
        <li><a href={% url 'add_genre_view' %}>ADD GENRE</a></li>
        <li><a href={% url 'album_list_view' %}>ALBUM LIST</a></li>
    </ul>
    <h2>Update the album:</h2>

    <h3>Artist(s): </h3>
        {% for artist in album.artist.all %}
        <p id="artist_list_p"><a href={% url 'artist_update_view' artist.id %}>{{ artist }}</a></p>
        {% endfor %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update the album"></form>
{% endblock %}

vinyl_market/templates/vinyl_market/artist_form.html
{% extends 'main.html' %}
{% block content %}
    <h2>Add new artist:</h2>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Artist"></form>

    <p id="artist_list_p">Artist list (click to edit):</p>
    <ul class="artist_list">
        {% for artist in artists|dictsort:"name" %}
            <li><a href={% url 'artist_update_view' artist.id %}>{{ artist.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

vinyl_market/templates/vinyl_market/artist_update_form.html
{% extends 'main.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update artist">
    </form>

    <p id="genre_list_p">Albums by {{ artist }}:</p>

    <table>
    {% for album in artist.album_set.all %}
    <p id="genre_list_p"><a href="{% url 'album_detail_view' album.id %}">{{ album }}</a></p>
    {% endfor %}
    </table>
{% endblock %}

vinyl_market/templates/vinyl_market/message_confirm_delete.html
{% extends 'main.html' %}
{% block content %}

    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete the message  ?</p>
        <p id="artist_list_p">"{{ message.message }}" by {{ message.sender }}</p>
        <p id="artist_list_p2"><button type="submit" value="Confirm">Confirm</button></p>

    </form>

{% endblock %}

vinyl_market/templates/vinyl_market/useroffer_list.html
{% extends 'main.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vinyl_market/style.css' %}">

{% block content %}
    <table id="market">
        <th>Album</th>
        <th>Artist</th>
        <th>Price</th>
        <th>Message user</th>

    {% for offer in object_list %}
        {% for artist in offer.album.artist.all %}
            <tr>
                <td>{{ offer.album.title }}</td>
                <td>{{ artist.name }}</td>
                <td>{{ offer.price }} &#8364;</td>
                <td><a href={% url 'sent_message' offer.album.user_id %}>&#9993;</a></td>
            </tr>
        {% endfor %}
        {% empty %}
            <p>No offers yet.</p>
    {% endfor %}
    </table>
{% endblock %}